### ISSUE TITLE
Doesn't work with .svelte files

### ISSUE THREAD

**Issue by atmosbear** [cybersonic/vscode_extension_copy_to#8]

**Comment by atmosbear** [comment]
Might be related to [this error](https://github.com/sveltejs/language-tools/issues/1187) in svelte's github?

The error I get is:
```
<semantic> TypeScript Server Error (5.2.0-dev.20230716)
Debug Failure. File /home/xxx/Desktop/svelte-fb/components/Fret.svelte has unknown extension.
Error: Debug Failure. File /home/xxx/Desktop/svelte-fb/components/Fret.svelte has unknown extension.
at extensionFromPath (/home/xxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230716/node_modules/typescript/lib/tsserver.js:21051:39)
at /home/xxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230716/node_modules/typescript/lib/tsserver.js:144691:221
at mapDefined (/home/xxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230716/node_modules/typescript/lib/tsserver.js:2667:22)
at Proxy.getMoveToRefactoringFileSuggestions (/home/xxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230716/node_modules/typescript/lib/tsserver.js:144691:19)
```

**Comment by cybersonic** [comment]
I had this set to CFML files, I have removed that, although I don't think we will fix the error above since they arent related. 
Give it another try and let me know how you go
